"""Emitter for project.godot."""

from collections import defaultdict
from typing import Any

from pygodot.emitters.values import gd_string, gd_value
from pygodot.input_keys import keycode_for
from pygodot.input_mouse import mouse_button_index_for
from pygodot.ir.model import IRInputAction, IRProject


class ProjectEmitter:
    def emit(self, project: IRProject) -> str:
        extra_settings = _settings_by_section(project.project_settings)
        application_extra = extra_settings.pop("application", [])
        lines = [
            "; Generated by pygodot.",
            "",
            "config_version=5",
            "",
            "[application]",
            "",
            f"config/name={gd_string(project.name)}",
            f"run/main_scene={gd_string(project.main_scene)}",
        ]
        if project.icon is not None:
            lines.append(f"config/icon={gd_string(project.icon.path)}")
        lines.extend(application_extra)
        if project.autoloads:
            lines.extend(["", "[autoload]", ""])
            for autoload in project.autoloads:
                lines.append(f"{autoload.name}={gd_string('*' + autoload.path)}")
        if project.input_actions:
            lines.extend(["", "[input]", ""])
            for action in project.input_actions:
                lines.extend(_emit_input_action(action))
        display_lines = []
        if project.window is not None:
            display_lines.extend(
                [
                    f"window/size/viewport_width={project.window.width}",
                    f"window/size/viewport_height={project.window.height}",
                ]
            )
            if project.window.stretch_mode is not None:
                display_lines.append(f"window/stretch/mode={gd_string(project.window.stretch_mode)}")
            if project.window.stretch_aspect is not None:
                display_lines.append(f"window/stretch/aspect={gd_string(project.window.stretch_aspect)}")
        display_lines.extend(extra_settings.pop("display", []))
        if display_lines:
            lines.extend(["", "[display]", "", *display_lines])
        for section in sorted(extra_settings):
            lines.extend(["", f"[{section}]", "", *extra_settings[section]])
        return "\n".join(lines).rstrip() + "\n"


def _emit_input_action(action: IRInputAction) -> list[str]:
    events = ", ".join(
        [
            *(_input_event_key(key) for key in action.keys),
            *(_input_event_mouse_button(button) for button in action.mouse_buttons),
        ]
    )
    return [
        f"{action.name}={{",
        '"deadzone": 0.5,',
        f'"events": [{events}]',
        "}",
    ]


def _input_event_key(key: str) -> str:
    keycode = keycode_for(key)
    if keycode is None:
        raise ValueError(f"Unsupported input key: {key!r}.")
    unicode_value = keycode if len(key) == 1 else 0
    return (
        'Object(InputEventKey,"resource_local_to_scene":false,'
        '"resource_name":"","device":-1,"window_id":0,'
        '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,'
        f'"pressed":false,"keycode":{keycode},"physical_keycode":0,'
        f'"key_label":0,"unicode":{unicode_value},"location":0,"echo":false,"script":null)'
    )


def _input_event_mouse_button(button: str) -> str:
    button_index = mouse_button_index_for(button)
    if button_index is None:
        raise ValueError(f"Unsupported input mouse button: {button!r}.")
    return (
        'Object(InputEventMouseButton,"resource_local_to_scene":false,'
        '"resource_name":"","device":-1,"window_id":0,'
        '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,'
        f'"pressed":false,"button_index":{button_index},'
        '"pressure":0.0,"double_click":false,"script":null)'
    )


def _settings_by_section(settings: tuple[Any, ...]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for setting in sorted(settings, key=lambda item: item.path):
        section, key = setting.path.split("/", 1)
        grouped[section].append(f"{key}={gd_value(setting.value)}")
    return dict(grouped)
