"""Emitter for project.godot."""

from pygodot.ir.model import IRProject
from pygodot.emitters.values import gd_string


class ProjectEmitter:
    def emit(self, project: IRProject) -> str:
        return (
            "; Generated by pygodot.\n"
            "\n"
            "config_version=5\n"
            "\n"
            "[application]\n"
            "\n"
            f"config/name={gd_string(project.name)}\n"
            f"run/main_scene={gd_string(project.main_scene)}\n"
        )
