"""Emitter for project.godot."""

from pygodot.emitters.values import gd_string
from pygodot.input_keys import keycode_for
from pygodot.input_mouse import mouse_button_index_for
from pygodot.ir.model import IRInputAction, IRProject


class ProjectEmitter:
    def emit(self, project: IRProject) -> str:
        lines = [
            "; Generated by pygodot.",
            "",
            "config_version=5",
            "",
            "[application]",
            "",
            f"config/name={gd_string(project.name)}",
            f"run/main_scene={gd_string(project.main_scene)}",
        ]
        if project.input_actions:
            lines.extend(["", "[input]", ""])
            for action in project.input_actions:
                lines.extend(_emit_input_action(action))
        if project.window is not None:
            lines.extend(
                [
                    "",
                    "[display]",
                    "",
                    f"window/size/viewport_width={project.window.width}",
                    f"window/size/viewport_height={project.window.height}",
                ]
            )
        return "\n".join(lines).rstrip() + "\n"


def _emit_input_action(action: IRInputAction) -> list[str]:
    events = ", ".join(
        [
            *(_input_event_key(key) for key in action.keys),
            *(_input_event_mouse_button(button) for button in action.mouse_buttons),
        ]
    )
    return [
        f"{action.name}={{",
        '"deadzone": 0.5,',
        f'"events": [{events}]',
        "}",
    ]


def _input_event_key(key: str) -> str:
    keycode = keycode_for(key)
    if keycode is None:
        raise ValueError(f"Unsupported input key: {key!r}.")
    unicode_value = keycode if len(key) == 1 else 0
    return (
        'Object(InputEventKey,"resource_local_to_scene":false,'
        '"resource_name":"","device":-1,"window_id":0,'
        '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,'
        f'"pressed":false,"keycode":{keycode},"physical_keycode":0,'
        f'"key_label":0,"unicode":{unicode_value},"location":0,"echo":false,"script":null)'
    )


def _input_event_mouse_button(button: str) -> str:
    button_index = mouse_button_index_for(button)
    if button_index is None:
        raise ValueError(f"Unsupported input mouse button: {button!r}.")
    return (
        'Object(InputEventMouseButton,"resource_local_to_scene":false,'
        '"resource_name":"","device":-1,"window_id":0,'
        '"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,'
        f'"pressed":false,"button_index":{button_index},'
        '"pressure":0.0,"double_click":false,"script":null)'
    )
