"""Public DSL objects."""

from pygodot.dsl.animation import (
    Animation,
    AnimationKey,
    ValueTrack,
    animation,
    key,
    value_track,
)
from pygodot.dsl.input import InputAction
from pygodot.dsl.generated_resources import GeneratedResource, label_settings, style_box_flat
from pygodot.dsl.nodes import (
    Area2D,
    AudioStreamPlayer,
    AnimationPlayer,
    Button,
    CenterContainer,
    CollisionShape2D,
    ColorRect,
    Control,
    GridContainer,
    HBoxContainer,
    HSeparator,
    Label,
    MarginContainer,
    Node,
    Node2D,
    Panel,
    RichTextLabel,
    Sprite2D,
    TextureRect,
    Timer,
    VBoxContainer,
    node,
    scene_instance,
)
from pygodot.dsl.resources import (
    ExternalResource,
    audio_stream,
    ext_resource,
    external_resource,
    font,
    packed_scene,
    shader,
    texture,
)
from pygodot.dsl.scene import Scene
from pygodot.dsl.settings import Autoload, ProjectSetting, WindowSettings
from pygodot.dsl.shapes import (
    CircleShape2D,
    RectangleShape2D,
    circle_shape_2d,
    rectangle_shape_2d,
)
from pygodot.dsl.script import Script
from pygodot.dsl.signal import SignalConnection, signal
from pygodot.dsl.subresources import SubResource, sub_resource
from pygodot.dsl.values import Color, NodePath, Rect2, StringName, Vec2, Vec3

__all__ = [
    "Animation",
    "AnimationKey",
    "AnimationPlayer",
    "Area2D",
    "AudioStreamPlayer",
    "Autoload",
    "Button",
    "CenterContainer",
    "CircleShape2D",
    "CollisionShape2D",
    "Color",
    "ColorRect",
    "Control",
    "ExternalResource",
    "GeneratedResource",
    "GridContainer",
    "HBoxContainer",
    "HSeparator",
    "InputAction",
    "Label",
    "MarginContainer",
    "Node",
    "Node2D",
    "NodePath",
    "Panel",
    "ProjectSetting",
    "Rect2",
    "RectangleShape2D",
    "RichTextLabel",
    "Scene",
    "Script",
    "SignalConnection",
    "Sprite2D",
    "StringName",
    "SubResource",
    "TextureRect",
    "Timer",
    "ValueTrack",
    "VBoxContainer",
    "Vec2",
    "Vec3",
    "WindowSettings",
    "audio_stream",
    "animation",
    "circle_shape_2d",
    "ext_resource",
    "external_resource",
    "font",
    "key",
    "label_settings",
    "node",
    "packed_scene",
    "rectangle_shape_2d",
    "scene_instance",
    "shader",
    "signal",
    "style_box_flat",
    "sub_resource",
    "texture",
    "value_track",
]
