from __future__ import annotations

import unittest

from pygodot.emitters.project import ProjectEmitter
from pygodot.ir.model import (
    IRAutoload,
    IRExternalResource,
    IRInputAction,
    IRProject,
    IRProjectSetting,
    IRWindowSettings,
)


class ProjectEmitterTests(unittest.TestCase):
    def test_project_emitter_snapshot(self) -> None:
        project = IRProject(name="GeneratedGame", main_scene="res://scenes/main.tscn")

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"
""",
        )

    def test_project_emitter_snapshot_with_input_actions(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            input_actions=(
                IRInputAction(name="jump", keys=("SPACE",)),
                IRInputAction(name="move_up", keys=("W", "UP")),
            ),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[input]

jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
move_up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":87,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194320,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
""",
        )

    def test_project_emitter_snapshot_with_window_settings(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            window=IRWindowSettings(width=800, height=600),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[display]

window/size/viewport_width=800
window/size/viewport_height=600
""",
        )

    def test_project_emitter_snapshot_with_autoloads_and_extra_settings(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            autoloads=(
                IRAutoload(
                    name="GameState",
                    path="res://scripts/singletons/game_state.gd",
                    resource_id="Script_scripts_singletons_game_state_gd",
                ),
                IRAutoload(
                    name="SceneChanger",
                    path="res://scripts/singletons/scene_changer.gd",
                    resource_id="Script_scripts_singletons_scene_changer_gd",
                ),
            ),
            icon=IRExternalResource(
                type="Texture2D",
                path="res://resources/icon.png",
                id="Texture2D_resources_icon_png",
            ),
            window=IRWindowSettings(
                width=540,
                height=750,
                stretch_mode="canvas_items",
                stretch_aspect="expand",
            ),
            project_settings=(
                IRProjectSetting("physics/common/enable_pause_aware_picking", True),
                IRProjectSetting("audio/output_latency/web", 200),
            ),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"
config/icon="res://resources/icon.png"

[autoload]

GameState="*res://scripts/singletons/game_state.gd"
SceneChanger="*res://scripts/singletons/scene_changer.gd"

[display]

window/size/viewport_width=540
window/size/viewport_height=750
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[audio]

output_latency/web=200

[physics]

common/enable_pause_aware_picking=true
""",
        )

    def test_project_emitter_snapshot_with_mouse_input_action(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            input_actions=(
                IRInputAction(name="shoot", keys=(), mouse_buttons=("LEFT",)),
                IRInputAction(name="inspect", keys=("E",), mouse_buttons=("RIGHT",)),
            ),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[input]

shoot={
"deadzone": 0.5,
"events": [Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"button_index":1,"pressure":0.0,"double_click":false,"script":null)]
}
inspect={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":69,"physical_keycode":0,"key_label":0,"unicode":69,"location":0,"echo":false,"script":null), Object(InputEventMouseButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"button_index":2,"pressure":0.0,"double_click":false,"script":null)]
}
""",
        )
