from __future__ import annotations

import json
import importlib.util
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from pygodot import (
    Button,
    Color,
    ColorRect,
    Game,
    Label,
    Node2D,
    NodePath,
    Node,
    InputAction,
    packed_scene,
    Rect2,
    Scene,
    Script,
    Vec2,
    Vec3,
    WindowSettings,
    ext_resource,
    signal,
    node,
    texture,
)
from pygodot.emitters.gdscript import GdScriptEmitter
from pygodot.emitters.project import ProjectEmitter
from pygodot.emitters.tscn import TscnEmitter
from pygodot.emitters.values import gd_value
from pygodot.errors import BuildError, ValidationError
from pygodot.godot_cli import check_project_run
from pygodot.ir.model import IRInputAction, IRProject, IRWindowSettings
from pygodot.ir.normalize import normalize_project, normalize_scene
from pygodot.ir.validate import validate_project, validate_scene


SNAPSHOTS_DIR = Path(__file__).parent / "snapshots"


def make_scene() -> Scene:
    script = Script(
        path="res://scripts/main.gd",
        extends="Node2D",
        body="""
        var counter := 0

        func _on_start_pressed() -> void:
            counter += 1
        """,
    )
    return Scene(
        path="res://scenes/main.tscn",
        root=Node2D(
            "Main",
            script=script,
            children=[
                Label("Title", text="Generated scene", position=(80, 60)),
                Button(
                    "StartButton",
                    text="Click me",
                    position=Vec2(80, 120),
                    signals=[signal("pressed", target=".", method="_on_start_pressed")],
                ),
            ],
        ),
    )


class DslNodeTests(unittest.TestCase):
    def test_node_helper_creates_generic_node(self) -> None:
        script = Script(
            path="res://scripts/panel.gd",
            extends="Control",
            body="func _ready() -> void:\n    pass",
        )
        signals = [signal("pressed", target=".", method="_on_pressed")]
        child = Label("Title", text="Hello")

        generic = node(
            "Panel",
            "Control",
            children=[child],
            script=script,
            signals=signals,
            position=Vec2(12, 24),
            visible=True,
        )

        self.assertEqual(generic.name, "Panel")
        self.assertEqual(generic.type, "Control")
        self.assertEqual(generic.props, {"position": Vec2(12, 24), "visible": True})
        self.assertEqual(generic.children, [child])
        self.assertIs(generic.script, script)
        self.assertEqual(generic.signals, signals)

    def test_color_rect_constructor_creates_color_rect_node(self) -> None:
        rect = ColorRect(
            "Panel",
            position=Vec2(10, 20),
            size=Vec2(200, 80),
            color=Color(0.1, 0.2, 0.3),
        )

        self.assertEqual(rect.name, "Panel")
        self.assertEqual(rect.type, "ColorRect")
        self.assertEqual(
            rect.props,
            {
                "position": Vec2(10, 20),
                "size": Vec2(200, 80),
                "color": Color(0.1, 0.2, 0.3),
            },
        )

    def test_script_from_file_declares_generated_source(self) -> None:
        script = Script.from_file(
            source="scripts/player.gd",
            path="res://scripts/player.gd",
            extends="Node2D",
        )

        self.assertEqual(script.source, "scripts/player.gd")
        self.assertEqual(script.path, "res://scripts/player.gd")
        self.assertEqual(script.extends, "Node2D")
        self.assertEqual(script.body, "")
        self.assertTrue(script.generated)


class ValueSerializationTests(unittest.TestCase):
    def test_serializes_common_godot_values(self) -> None:
        self.assertEqual(gd_value("hello"), '"hello"')
        self.assertEqual(gd_value(True), "true")
        self.assertEqual(gd_value(None), "null")
        self.assertEqual(gd_value((1, 2)), "Vector2(1, 2)")
        self.assertEqual(gd_value((1, 2, 3)), "Vector3(1, 2, 3)")
        self.assertEqual(gd_value(Vec2(80, 120)), "Vector2(80, 120)")
        self.assertEqual(gd_value(Vec3(1, 2, 3)), "Vector3(1, 2, 3)")
        self.assertEqual(gd_value(Rect2(1, 2, 30, 40)), "Rect2(1, 2, 30, 40)")
        self.assertEqual(gd_value(Color(1, 0.5, 0.25)), "Color(1, 0.5, 0.25, 1.0)")
        self.assertEqual(gd_value(NodePath("../Player")), 'NodePath("../Player")')


class EmitterSnapshotTests(unittest.TestCase):
    def test_project_emitter_snapshot(self) -> None:
        project = IRProject(name="GeneratedGame", main_scene="res://scenes/main.tscn")

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"
""",
        )

    def test_project_emitter_snapshot_with_input_actions(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            input_actions=(
                IRInputAction(name="jump", keys=("SPACE",)),
                IRInputAction(name="move_up", keys=("W", "UP")),
            ),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[input]

jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
move_up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":87,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194320,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
""",
        )

    def test_project_emitter_snapshot_with_window_settings(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            window=IRWindowSettings(width=800, height=600),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[display]

window/size/viewport_width=800
window/size/viewport_height=600
""",
        )

    def test_gdscript_emitter_snapshot(self) -> None:
        script = normalize_scene(make_scene()).root.script
        assert script is not None

        self.assertEqual(
            GdScriptEmitter().emit(script),
            """extends Node2D

var counter := 0

func _on_start_pressed() -> void:
    counter += 1
""",
        )

    def test_tscn_emitter_snapshot(self) -> None:
        scene = normalize_scene(make_scene())

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="Script_scripts_main_gd"]

[node name="Main" type="Node2D"]
script = ExtResource("Script_scripts_main_gd")

[node name="Title" type="Label" parent="."]
position = Vector2(80, 60)
text = "Generated scene"

[node name="StartButton" type="Button" parent="."]
position = Vector2(80, 120)
text = "Click me"


[connection signal="pressed" from="StartButton" to="." method="_on_start_pressed"]
""",
        )

    def test_minimal_scene_file_snapshot(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/minimal.tscn",
                root=Node2D(
                    "Main",
                    children=[
                        Label("Title", text="Hello snapshots"),
                    ],
                ),
            )
        )

        self.assert_matches_snapshot(
            "minimal_scene.tscn",
            TscnEmitter().emit(scene),
        )

    def test_pong_scene_file_snapshot(self) -> None:
        pong = _load_example_game("pong")
        scene = normalize_scene(_find_scene(pong.game, "res://scenes/pong.tscn"))

        self.assert_matches_snapshot(
            "pong_scene.tscn",
            TscnEmitter().emit(scene),
        )

    def test_pong_menu_scene_file_snapshot(self) -> None:
        pong = _load_example_game("pong")
        scene = normalize_scene(_find_scene(pong.game, "res://scenes/menu.tscn"))

        self.assert_matches_snapshot(
            "pong_menu_scene.tscn",
            TscnEmitter().emit(scene),
        )

    def test_pong_script_file_snapshot(self) -> None:
        pong = _load_example_game("pong")

        self.assert_matches_snapshot(
            "pong_script.gd",
            _build_example_script(pong.game, "scripts/pong.gd"),
        )

    def test_snake_scene_file_snapshot(self) -> None:
        snake = _load_example_game("snake")
        scene = normalize_scene(snake.game.scenes[0])

        self.assert_matches_snapshot(
            "snake_scene.tscn",
            TscnEmitter().emit(scene),
        )

    def test_snake_script_file_snapshot(self) -> None:
        snake = _load_example_game("snake")

        self.assert_matches_snapshot(
            "snake_script.gd",
            _build_example_script(snake.game, "scripts/snake.gd"),
        )

    def test_tscn_emitter_snapshot_with_external_resource_property(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=ext_resource("res://assets/icon.svg", type="Texture2D"),
                ),
            )
        )

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Texture2D" path="res://assets/icon.svg" id="Texture2D_assets_icon_svg"]

[node name="Main" type="Node2D"]
icon = ExtResource("Texture2D_assets_icon_svg")
""",
        )

    def test_tscn_emitter_snapshot_with_rect2_property(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    region_rect=Rect2(0, 0, 16, 32),
                ),
            )
        )

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene format=3]

[node name="Main" type="Node2D"]
region_rect = Rect2(0, 0, 16, 32)
""",
        )

    def test_tscn_emitter_snapshot_with_referenced_script(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    script=Script.reference(
                        "res://manual/player.gd",
                        extends="Node2D",
                    ),
                ),
            )
        )

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://manual/player.gd" id="Script_manual_player_gd"]

[node name="Main" type="Node2D"]
script = ExtResource("Script_manual_player_gd")
""",
        )

    def test_normalize_collects_external_resource_properties(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=ext_resource("res://assets/icon.svg", type="Texture2D"),
                ),
            )
        )

        self.assertEqual(len(scene.external_resources), 1)
        resource = scene.external_resources[0]
        self.assertEqual(resource.type, "Texture2D")
        self.assertEqual(resource.path, "res://assets/icon.svg")
        self.assertEqual(resource.id, "Texture2D_assets_icon_svg")

    def test_typed_external_resource_helpers(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=texture("res://assets/icon.svg"),
                    next_scene=packed_scene("res://scenes/menu.tscn"),
                ),
            )
        )

        self.assertEqual(
            [(resource.type, resource.path, resource.id) for resource in scene.external_resources],
            [
                ("PackedScene", "res://scenes/menu.tscn", "PackedScene_scenes_menu_tscn"),
                ("Texture2D", "res://assets/icon.svg", "Texture2D_assets_icon_svg"),
            ],
        )

    def assert_matches_snapshot(self, snapshot_name: str, actual: str) -> None:
        expected = (SNAPSHOTS_DIR / snapshot_name).read_text(encoding="utf-8")
        self.assertEqual(actual, expected)

    def test_external_resources_dedupe_by_type_and_path(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node(
                    name="Main",
                    type="Node",
                    props={
                        "first": texture("res://assets/icon.svg"),
                        "second": texture("res://assets/icon.svg"),
                        "same_path_other_type": ext_resource(
                            "res://assets/icon.svg",
                            type="CompressedTexture2D",
                        ),
                    },
                ),
            )
        )

        self.assertEqual(
            [(resource.type, resource.path, resource.id) for resource in scene.external_resources],
            [
                (
                    "CompressedTexture2D",
                    "res://assets/icon.svg",
                    "CompressedTexture2D_assets_icon_svg",
                ),
                ("Texture2D", "res://assets/icon.svg", "Texture2D_assets_icon_svg"),
            ],
        )


class ValidationTests(unittest.TestCase):
    def test_duplicate_sibling_node_names_are_rejected(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                children=[
                    Label("Title", text="One"),
                    Label("Title", text="Two"),
                ],
            ),
        )

        with self.assertRaisesRegex(ValidationError, "Duplicate child node name"):
            validate_scene(normalize_scene(scene))

    def test_generated_script_body_must_not_be_empty(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                script=Script(path="res://scripts/main.gd", extends="Node2D"),
            ),
        )

        with self.assertRaisesRegex(
            ValidationError,
            "Generated script body must not be empty: scene='res://scenes/main.tscn', "
            "node='.', script_path='res://scripts/main.gd'",
        ):
            validate_scene(normalize_scene(scene))

    def test_unsupported_property_value_error_includes_context(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                metadata=object(),
            ),
        )

        with self.assertRaisesRegex(
            ValidationError,
            "Unsupported value for property 'metadata': scene='res://scenes/main.tscn', "
            "node='.', value=.*value_type=object",
        ):
            validate_scene(normalize_scene(scene))

    def test_main_scene_error_includes_registered_scenes(self) -> None:
        game = Game(
            name="GeneratedGame",
            source_root=Path("."),
            build_dir=Path("build/godot_project"),
            main_scene="res://missing.tscn",
        )
        game.add_scene(make_scene())

        with self.assertRaisesRegex(
            ValidationError,
            "main_scene='res://missing.tscn'.*registered_scenes=\\['res://scenes/main.tscn'\\]",
        ):
            game.build()

    def test_input_action_names_are_validated(self) -> None:
        project = normalize_project(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            scenes=[make_scene()],
            input_actions=[InputAction("move-up", ("W",))],
        )

        with self.assertRaisesRegex(ValidationError, "Input action name"):
            validate_project(project)

    def test_input_action_keys_are_validated(self) -> None:
        project = normalize_project(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            scenes=[make_scene()],
            input_actions=[InputAction("move_up", ("NOT_A_KEY",))],
        )

        with self.assertRaisesRegex(ValidationError, "Unsupported input action key"):
            validate_project(project)

    def test_duplicate_input_actions_are_rejected(self) -> None:
        project = normalize_project(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            scenes=[make_scene()],
            input_actions=[
                InputAction("jump", ("SPACE",)),
                InputAction("jump", ("W",)),
            ],
        )

        with self.assertRaisesRegex(ValidationError, "Duplicate input action name"):
            validate_project(project)

    def test_window_size_is_validated(self) -> None:
        project = normalize_project(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            scenes=[make_scene()],
            window=WindowSettings(size=Vec2(0, 600)),
        )

        with self.assertRaisesRegex(ValidationError, "Window size must be positive"):
            validate_project(project)

    def test_generated_script_cannot_define_body_and_source(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                script=Script(
                    path="res://scripts/main.gd",
                    extends="Node2D",
                    body="func _ready() -> void:\n    pass",
                    source="scripts/main.gd",
                ),
            ),
        )

        with self.assertRaisesRegex(ValidationError, "either body or source"):
            validate_scene(normalize_scene(scene))


class BuildTests(unittest.TestCase):
    def test_game_build_writes_expected_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(make_scene())

            result = game.build()

            self.assertEqual(result.project_dir, build_dir)
            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                [".pygodot/manifest.json", "project.godot", "scenes/main.tscn", "scripts/main.gd"],
            )
            self.assertTrue((build_dir / "project.godot").exists())
            self.assertTrue((build_dir / "scenes" / "main.tscn").exists())
            self.assertTrue((build_dir / "scripts" / "main.gd").exists())
            self.assertEqual(result.manifest_path, build_dir / ".pygodot" / "manifest.json")

    def test_game_build_output_is_stable_across_repeated_builds(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(make_scene())

            game.build()
            first = _read_generated_files(build_dir)
            game.build()
            second = _read_generated_files(build_dir)

            self.assertEqual(second, first)

    def test_game_build_does_not_write_referenced_manual_scripts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            manual_script = Path(tmp) / "manual" / "player.gd"
            manual_script.parent.mkdir(parents=True)
            manual_script.write_text("extends Node2D\n", encoding="utf-8")
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        script=Script.reference(
                            "res://manual/player.gd",
                            extends="Node2D",
                        ),
                    ),
                )
            )

            result = game.build()

            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                [".pygodot/manifest.json", "project.godot", "scenes/main.tscn"],
            )
            self.assertEqual(result.generated_scripts, [])
            self.assertFalse((build_dir / "manual" / "player.gd").exists())
            self.assertIn(
                'path="res://manual/player.gd"',
                (build_dir / "scenes" / "main.tscn").read_text(encoding="utf-8"),
            )

    def test_game_build_writes_generated_script_from_source_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source_root = Path(tmp) / "source"
            source_script = source_root / "scripts" / "player.gd"
            source_script.parent.mkdir(parents=True)
            source_script.write_text(
                "func _ready() -> void:\n    $Label.text = \"Loaded from file\"\n",
                encoding="utf-8",
            )
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=source_root,
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        script=Script.from_file(
                            source="scripts/player.gd",
                            path="res://scripts/player.gd",
                            extends="Node2D",
                        ),
                    ),
                )
            )

            result = game.build()

            generated_script = build_dir / "scripts" / "player.gd"
            self.assertEqual(result.generated_scripts, [generated_script])
            self.assertEqual(
                generated_script.read_text(encoding="utf-8"),
                """# Generated by pygodot. Do not edit by hand.

extends Node2D

func _ready() -> void:
    $Label.text = "Loaded from file"
""",
            )

    def test_game_build_rejects_missing_generated_script_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        script=Script.from_file(
                            source="scripts/missing.gd",
                            path="res://scripts/main.gd",
                            extends="Node2D",
                        ),
                    ),
                )
            )

            with self.assertRaisesRegex(BuildError, "source file does not exist"):
                game.build()

    def test_game_build_rejects_unsafe_generated_script_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        script=Script.from_file(
                            source="../outside.gd",
                            path="res://scripts/main.gd",
                            extends="Node2D",
                        ),
                    ),
                )
            )

            with self.assertRaisesRegex(BuildError, "cannot leave source root"):
                game.build()

    def test_game_build_copies_existing_external_assets_and_writes_manifest(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            source_root = Path(tmp) / "source"
            build_dir = Path(tmp) / "godot_project"
            asset_path = source_root / "assets" / "icon.svg"
            asset_path.parent.mkdir(parents=True)
            asset_path.write_text("<svg></svg>\n", encoding="utf-8")

            game = Game(
                name="GeneratedGame",
                source_root=source_root,
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        icon=texture("res://assets/icon.svg"),
                    ),
                )
            )

            result = game.build()

            copied_asset = build_dir / "assets" / "icon.svg"
            self.assertEqual(result.copied_resources, [copied_asset])
            self.assertEqual(copied_asset.read_text(encoding="utf-8"), "<svg></svg>\n")

            manifest_path = build_dir / ".pygodot" / "manifest.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            self.assertEqual(result.manifest_path, manifest_path)
            self.assertIn(".pygodot/manifest.json", manifest["generated_files"])
            self.assertEqual(
                manifest["external_resources"],
                [
                    {
                        "copied": True,
                        "id": "Texture2D_assets_icon_svg",
                        "path": "res://assets/icon.svg",
                        "type": "Texture2D",
                    }
                ],
            )

    def test_game_build_rejects_unsafe_res_paths(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://../main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://../main.tscn",
                    root=Node2D("Main"),
                )
            )

            with self.assertRaisesRegex(
                BuildError,
                "Unsafe res:// path cannot leave project root: path='res://../main.tscn'",
            ):
                game.build()

    def test_check_project_run_builds_headless_command(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_dir = Path(tmp)
            (project_dir / "pygodot_check_run.log").write_text(
                "Loading resource: res://scenes/main.tscn\n",
                encoding="utf-8",
            )

            with patch("pygodot.godot_cli.subprocess.run") as run:
                run.return_value = subprocess.CompletedProcess(
                    args=[],
                    returncode=0,
                    stdout="fake godot ok\n",
                    stderr="",
                )

                result = check_project_run(
                    project_dir,
                    godot_bin="godot",
                    scene="res://scenes/main.tscn",
                    frames=3,
                )

            self.assertEqual(result.returncode, 0)
            self.assertIn("--headless", result.command)
            self.assertIn("--scene", result.command)
            self.assertIn("res://scenes/main.tscn", result.command)
            self.assertIn("--quit-after", result.command)
            self.assertIn("3", result.command)
            self.assertIn("fake godot ok", result.stdout)
            self.assertIn("Loading resource", result.log_text)

    def test_pong_example_builds_menu_and_game_scenes(self) -> None:
        pong = _load_example_game("pong")

        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            pong.game.build_dir = build_dir

            result = pong.game.build()

            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                [
                    ".pygodot/manifest.json",
                    "project.godot",
                    "scenes/menu.tscn",
                    "scenes/pong.tscn",
                    "scripts/menu.gd",
                    "scripts/pong.gd",
                ],
            )

            menu_scene_text = (build_dir / "scenes" / "menu.tscn").read_text(encoding="utf-8")
            menu_script_text = (build_dir / "scripts" / "menu.gd").read_text(encoding="utf-8")
            scene_text = (build_dir / "scenes" / "pong.tscn").read_text(encoding="utf-8")
            script_text = (build_dir / "scripts" / "pong.gd").read_text(encoding="utf-8")

            self.assertIn('[node name="Menu" type="Control"]', menu_scene_text)
            self.assertIn('[node name="StartButton" type="Button" parent="."]', menu_scene_text)
            self.assertIn(
                '[connection signal="pressed" from="StartButton" to="." method="_on_start_pressed"]',
                menu_scene_text,
            )
            self.assertIn('change_scene_to_file("res://scenes/pong.tscn")', menu_script_text)
            self.assertIn("get_tree().quit()", menu_script_text)

            self.assertIn('[node name="Main" type="Node2D"]', scene_text)
            self.assertIn('[node name="Ball" type="ColorRect" parent="."]', scene_text)
            self.assertIn('[node name="HelpText" type="Label" parent="."]', scene_text)
            self.assertIn("func _process(delta: float) -> void:", script_text)
            self.assertIn('Input.is_action_pressed("left_up")', script_text)
            self.assertIn('Input.is_action_just_pressed("restart")', script_text)
            self.assertIn("func reset_ball(direction: int) -> void:", script_text)

            project_text = (build_dir / "project.godot").read_text(encoding="utf-8")
            self.assertIn('run/main_scene="res://scenes/menu.tscn"', project_text)
            self.assertIn("[display]", project_text)
            self.assertIn("window/size/viewport_width=800", project_text)
            self.assertIn("window/size/viewport_height=600", project_text)
            self.assertIn("[input]", project_text)
            self.assertIn("left_up={", project_text)
            self.assertIn('"keycode":87', project_text)
            self.assertIn("right_down={", project_text)
            self.assertIn('"keycode":4194322', project_text)

    def test_snake_example_builds_draw_based_scene(self) -> None:
        snake = _load_example_game("snake")

        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            snake.game.build_dir = build_dir

            result = snake.game.build()

            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                [".pygodot/manifest.json", "project.godot", "scenes/snake.tscn", "scripts/snake.gd"],
            )

            scene_text = (build_dir / "scenes" / "snake.tscn").read_text(encoding="utf-8")
            script_text = (build_dir / "scripts" / "snake.gd").read_text(encoding="utf-8")
            project_text = (build_dir / "project.godot").read_text(encoding="utf-8")

            self.assertIn('[node name="Snake" type="Node2D"]', scene_text)
            self.assertIn("func _draw() -> void:", script_text)
            self.assertIn('Input.is_action_just_pressed("move_up")', script_text)
            self.assertIn("draw_cell(food", script_text)
            self.assertIn('run/main_scene="res://scenes/snake.tscn"', project_text)
            self.assertIn("window/size/viewport_width=672", project_text)
            self.assertIn("window/size/viewport_height=560", project_text)
            self.assertIn("move_left={", project_text)
            self.assertIn('"keycode":65', project_text)


def _read_generated_files(build_dir: Path) -> dict[str, str]:
    return {
        path.relative_to(build_dir).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(build_dir.rglob("*"))
        if path.is_file()
    }


def _load_example_game(name: str):
    path = Path(__file__).parents[1] / "examples" / name / "game.py"
    spec = importlib.util.spec_from_file_location(f"pygodot_example_{name}", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load example module from {path}.")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _find_scene(game: Game, path: str) -> Scene:
    for scene in game.scenes:
        if scene.path == path:
            return scene
    raise AssertionError(f"Missing scene: {path}")


def _build_example_script(game: Game, relative_path: str) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        build_dir = Path(tmp) / "godot_project"
        game.build_dir = build_dir
        game.build()
        return (build_dir / relative_path).read_text(encoding="utf-8")


if __name__ == "__main__":
    unittest.main()
