from __future__ import annotations

import unittest

from pygodot.emitters.project import ProjectEmitter
from pygodot.ir.model import IRInputAction, IRProject, IRWindowSettings


class ProjectEmitterTests(unittest.TestCase):
    def test_project_emitter_snapshot(self) -> None:
        project = IRProject(name="GeneratedGame", main_scene="res://scenes/main.tscn")

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"
""",
        )

    def test_project_emitter_snapshot_with_input_actions(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            input_actions=(
                IRInputAction(name="jump", keys=("SPACE",)),
                IRInputAction(name="move_up", keys=("W", "UP")),
            ),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[input]

jump={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
move_up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":87,"physical_keycode":0,"key_label":0,"unicode":87,"location":0,"echo":false,"script":null), Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194320,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)]
}
""",
        )

    def test_project_emitter_snapshot_with_window_settings(self) -> None:
        project = IRProject(
            name="GeneratedGame",
            main_scene="res://scenes/main.tscn",
            window=IRWindowSettings(width=800, height=600),
        )

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"

[display]

window/size/viewport_width=800
window/size/viewport_height=600
""",
        )
