from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from pygodot import (
    Button,
    Color,
    Game,
    Label,
    Node2D,
    NodePath,
    Node,
    packed_scene,
    Scene,
    Script,
    Vec2,
    Vec3,
    ext_resource,
    signal,
    texture,
)
from pygodot.emitters.gdscript import GdScriptEmitter
from pygodot.emitters.project import ProjectEmitter
from pygodot.emitters.tscn import TscnEmitter
from pygodot.emitters.values import gd_value
from pygodot.errors import ValidationError
from pygodot.ir.model import IRProject
from pygodot.ir.normalize import normalize_scene
from pygodot.ir.validate import validate_scene


def make_scene() -> Scene:
    script = Script(
        path="res://scripts/main.gd",
        extends="Node2D",
        body="""
        var counter := 0

        func _on_start_pressed() -> void:
            counter += 1
        """,
    )
    return Scene(
        path="res://scenes/main.tscn",
        root=Node2D(
            "Main",
            script=script,
            children=[
                Label("Title", text="Generated scene", position=(80, 60)),
                Button(
                    "StartButton",
                    text="Click me",
                    position=Vec2(80, 120),
                    signals=[signal("pressed", target=".", method="_on_start_pressed")],
                ),
            ],
        ),
    )


class ValueSerializationTests(unittest.TestCase):
    def test_serializes_common_godot_values(self) -> None:
        self.assertEqual(gd_value("hello"), '"hello"')
        self.assertEqual(gd_value(True), "true")
        self.assertEqual(gd_value(None), "null")
        self.assertEqual(gd_value((1, 2)), "Vector2(1, 2)")
        self.assertEqual(gd_value((1, 2, 3)), "Vector3(1, 2, 3)")
        self.assertEqual(gd_value(Vec2(80, 120)), "Vector2(80, 120)")
        self.assertEqual(gd_value(Vec3(1, 2, 3)), "Vector3(1, 2, 3)")
        self.assertEqual(gd_value(Color(1, 0.5, 0.25)), "Color(1, 0.5, 0.25, 1.0)")
        self.assertEqual(gd_value(NodePath("../Player")), 'NodePath("../Player")')


class EmitterSnapshotTests(unittest.TestCase):
    def test_project_emitter_snapshot(self) -> None:
        project = IRProject(name="GeneratedGame", main_scene="res://scenes/main.tscn")

        self.assertEqual(
            ProjectEmitter().emit(project),
            """; Generated by pygodot.

config_version=5

[application]

config/name="GeneratedGame"
run/main_scene="res://scenes/main.tscn"
""",
        )

    def test_gdscript_emitter_snapshot(self) -> None:
        script = normalize_scene(make_scene()).root.script
        assert script is not None

        self.assertEqual(
            GdScriptEmitter().emit(script),
            """extends Node2D

var counter := 0

func _on_start_pressed() -> void:
    counter += 1
""",
        )

    def test_tscn_emitter_snapshot(self) -> None:
        scene = normalize_scene(make_scene())

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="Script_scripts_main_gd"]

[node name="Main" type="Node2D"]
script = ExtResource("Script_scripts_main_gd")

[node name="Title" type="Label" parent="."]
position = Vector2(80, 60)
text = "Generated scene"

[node name="StartButton" type="Button" parent="."]
position = Vector2(80, 120)
text = "Click me"


[connection signal="pressed" from="StartButton" to="." method="_on_start_pressed"]
""",
        )

    def test_tscn_emitter_snapshot_with_external_resource_property(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=ext_resource("res://assets/icon.svg", type="Texture2D"),
                ),
            )
        )

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Texture2D" path="res://assets/icon.svg" id="Texture2D_assets_icon_svg"]

[node name="Main" type="Node2D"]
icon = ExtResource("Texture2D_assets_icon_svg")
""",
        )

    def test_tscn_emitter_snapshot_with_referenced_script(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    script=Script.reference(
                        "res://manual/player.gd",
                        extends="Node2D",
                    ),
                ),
            )
        )

        self.assertEqual(
            TscnEmitter().emit(scene),
            """[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://manual/player.gd" id="Script_manual_player_gd"]

[node name="Main" type="Node2D"]
script = ExtResource("Script_manual_player_gd")
""",
        )

    def test_normalize_collects_external_resource_properties(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=ext_resource("res://assets/icon.svg", type="Texture2D"),
                ),
            )
        )

        self.assertEqual(len(scene.external_resources), 1)
        resource = scene.external_resources[0]
        self.assertEqual(resource.type, "Texture2D")
        self.assertEqual(resource.path, "res://assets/icon.svg")
        self.assertEqual(resource.id, "Texture2D_assets_icon_svg")

    def test_typed_external_resource_helpers(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node2D(
                    "Main",
                    icon=texture("res://assets/icon.svg"),
                    next_scene=packed_scene("res://scenes/menu.tscn"),
                ),
            )
        )

        self.assertEqual(
            [(resource.type, resource.path, resource.id) for resource in scene.external_resources],
            [
                ("PackedScene", "res://scenes/menu.tscn", "PackedScene_scenes_menu_tscn"),
                ("Texture2D", "res://assets/icon.svg", "Texture2D_assets_icon_svg"),
            ],
        )

    def test_external_resources_dedupe_by_type_and_path(self) -> None:
        scene = normalize_scene(
            Scene(
                path="res://scenes/main.tscn",
                root=Node(
                    name="Main",
                    type="Node",
                    props={
                        "first": texture("res://assets/icon.svg"),
                        "second": texture("res://assets/icon.svg"),
                        "same_path_other_type": ext_resource(
                            "res://assets/icon.svg",
                            type="CompressedTexture2D",
                        ),
                    },
                ),
            )
        )

        self.assertEqual(
            [(resource.type, resource.path, resource.id) for resource in scene.external_resources],
            [
                (
                    "CompressedTexture2D",
                    "res://assets/icon.svg",
                    "CompressedTexture2D_assets_icon_svg",
                ),
                ("Texture2D", "res://assets/icon.svg", "Texture2D_assets_icon_svg"),
            ],
        )


class ValidationTests(unittest.TestCase):
    def test_duplicate_sibling_node_names_are_rejected(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                children=[
                    Label("Title", text="One"),
                    Label("Title", text="Two"),
                ],
            ),
        )

        with self.assertRaisesRegex(ValidationError, "Duplicate child node name"):
            validate_scene(normalize_scene(scene))

    def test_generated_script_body_must_not_be_empty(self) -> None:
        scene = Scene(
            path="res://scenes/main.tscn",
            root=Node2D(
                "Main",
                script=Script(path="res://scripts/main.gd", extends="Node2D"),
            ),
        )

        with self.assertRaisesRegex(ValidationError, "Generated script body must not be empty"):
            validate_scene(normalize_scene(scene))


class BuildTests(unittest.TestCase):
    def test_game_build_writes_expected_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(make_scene())

            result = game.build()

            self.assertEqual(result.project_dir, build_dir)
            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                ["project.godot", "scenes/main.tscn", "scripts/main.gd"],
            )
            self.assertTrue((build_dir / "project.godot").exists())
            self.assertTrue((build_dir / "scenes" / "main.tscn").exists())
            self.assertTrue((build_dir / "scripts" / "main.gd").exists())

    def test_game_build_output_is_stable_across_repeated_builds(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(make_scene())

            game.build()
            first = _read_generated_files(build_dir)
            game.build()
            second = _read_generated_files(build_dir)

            self.assertEqual(second, first)

    def test_game_build_does_not_write_referenced_manual_scripts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            build_dir = Path(tmp) / "godot_project"
            game = Game(
                name="GeneratedGame",
                source_root=Path(tmp),
                build_dir=build_dir,
                main_scene="res://scenes/main.tscn",
            )
            game.add_scene(
                Scene(
                    path="res://scenes/main.tscn",
                    root=Node2D(
                        "Main",
                        script=Script.reference(
                            "res://manual/player.gd",
                            extends="Node2D",
                        ),
                    ),
                )
            )

            result = game.build()

            self.assertEqual(
                sorted(path.relative_to(build_dir).as_posix() for path in result.written_files),
                ["project.godot", "scenes/main.tscn"],
            )
            self.assertEqual(result.generated_scripts, [])
            self.assertFalse((build_dir / "manual" / "player.gd").exists())
            self.assertIn(
                'path="res://manual/player.gd"',
                (build_dir / "scenes" / "main.tscn").read_text(encoding="utf-8"),
            )


def _read_generated_files(build_dir: Path) -> dict[str, str]:
    return {
        path.relative_to(build_dir).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(build_dir.rglob("*"))
        if path.is_file()
    }


if __name__ == "__main__":
    unittest.main()
